---
title: New Romney Country Fayre
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
    fields:
      - {label: "Heading", name: "Heading", widget: "string"}
  uploads:
    title: Uploads
    output: true
name: New Romney Country Fayre
email: admin@newromneycountryfayre.co.uk
description: New Romney Country Fayre - The largest FREE event on Romney Marsh, Kent
baseurl: ""
url: http://newromneycountryfayre.co.uk
markdown: kramdown
rouge: true
plugins:
- jekyll-feed
